### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by pravj** [razorpay/razorpay-opencart#1]
Hi Razorpay,

Found a little [typo in the README](https://github.com/razorpay/razorpay-opencart/blob/master/README.md#razorpay-payment-extension-for-opencart), not worth an issue though.

> This extension utilizes Razorpay API and provides seamless integration with ~~Ooencart~~ Opencart, allowing payments for Indian merchants via Credit Cards, Debit Cards, Net Banking (supports 3D Secure) without redirecting away from the opencart site.

**Comment by shashankkumar** [comment]
Fixed. Thanks for the report.
