### ISSUE TITLE
Email won't show razorpay image

### ISSUE THREAD

**Issue by cartbinder** [razorpay/razorpay-opencart#105]
The heading title of the Razorpay front end is:
catalog/language/en-gb/extension/payment/razorpay.php

Pay by Razorpay <br> <a href="https://www.razorpay.com" target="_blank"><img src="https://cdn.razorpay.com/static/assets/logo/payment_method.svg" alt="Razorpay" title="Razorpay" style="border: 1px solid #EEEEEE;margin-top: 5px" /></a>

As you can see this is an SVG image. And most email apps would reject SVG images. And it would look bad. Please either remove this image or add some png / jpeg image.

**Comment by cartbinder** [comment]
![-1-WhatsApp](https://user-images.githubusercontent.com/17376201/181903561-903b12b2-735b-441e-809f-f3faa6d2d63e.png)

**Comment by abdulwahidsharief** [comment]
@cartbinder image is removed in version [5.1.4](https://github.com/razorpay/razorpay-opencart/releases/tag/opencart3-5.1.4) please install the latest version
