### ISSUE TITLE
Not working in Opencart 4

### ISSUE THREAD

**Issue by RajatJain4061** [razorpay/razorpay-opencart#111]
I have created my opencart store with Opencart 4 version. I am not able to use this older version with my setup.

**Comment by VishalKumarSahu** [comment]
Did you install OC4 or Upgrade OC3 to OC4?

**Comment by mergosoftpvtltd** [comment]
Yes, Opencart 4 version not working.

**Comment by abdulwahidsharief** [comment]
support for opencart 4 was released on sep 28, 2023 
https://github.com/razorpay/razorpay-opencart/releases/tag/opencart4-6.0.0
