### ISSUE TITLE
Opencart 2.2

### ISSUE THREAD

**Issue by Temjenwapang** [razorpay/razorpay-opencart#114]
[razorpay-opencart_5.0.2.ocmod.zip](https://github.com/razorpay/razorpay-opencart/releases/download/opencart3-1.0.5/razorpay-opencart_5.0.2.ocmod.zip) Will this version work for Opencart 2.2

**Comment by abdulwahidsharief** [comment]
@Temjenwapang please follow [razorpay docs](https://betasite.razorpay.com/docs/razorpay/IN/payments-pg-plugins-opencart/payments/payment-gateway/ecommerce-plugins/open-cart/build-integration/#step-1-install-plugin)
https://github.com/razorpay/razorpay-opencart/releases/tag/opencart2-3.0.0
