### ISSUE TITLE
Support for Opencart 4

### ISSUE THREAD

**Issue by nirupbbnk** [razorpay/razorpay-opencart#122]
Hi Team,
We wanted to integrate razorpay  with Opencart 4. Currently I see its supported till version 3.
Can I know expected timeline. 
Also is there any alternative to integrate razorpay PG with opencart4 as it uses PHP and you guys have PHP solution.
Thanks in advance.

**Comment by ramth05** [comment]
Hi @nirupbbnk ,

Yes, we have already added it in our dev roadmap. Will share the ETA by mid of next week.
~Ram

**Comment by Developermayank** [comment]
Kindly update it asap for opencart 4.x

**Comment by ZateLabClients** [comment]
@nirupbbnk 

Any updates regarding opencart  4 support?

**Comment by ramth05** [comment]
@ZateLabClients ,

Yes, it's already in development and will be available in first week of Oct.

**Comment by ZateLabClients** [comment]
> 

Thank you for the update

**Comment by abdulwahidsharief** [comment]
@ZateLabClients https://github.com/razorpay/razorpay-opencart/releases/tag/opencart4-6.0.3
