### ISSUE TITLE
Support for OC 1.5.6.4

### ISSUE THREAD

**Issue by qfx007** [razorpay/razorpay-opencart#152]
Hello,
I am using Opencart ver 1.5.6.4  where can i find integration extension for the same?
Thanks.

**Comment by abdulwahidsharief** [comment]
@qfx007 please check [razorpay opencart integration docs ](https://betasite.razorpay.com/docs/razorpay/IN/payments-pg-plugins-opencart/payments/payment-gateway/ecommerce-plugins/open-cart/build-integration/#step-1-install-plugin) release tag : [opencart1.5-1.0.0](https://github.com/razorpay/razorpay-opencart/releases/tag/opencart1.5-1.0.0)
