### ISSUE TITLE
Fatal error: require_once(): Failed opening required

### ISSUE THREAD

**Issue by boja2015** [razorpay/razorpay-opencart#19]
getting error on order success return url

url
/index.php?route=payment/razorpay/callback

error message
Fatal error: require_once(): Failed opening required '........./catalog/controller/payment/../../../../system/library/razorpay-sdk/Razorpay.php' (include_path='.:/usr/local/php71/pear') in ....../catalog/controller/payment/razorpay.php on line 3

**Comment by mayankamencherla** [comment]
@boja2015 Could you please change 
`require_once __DIR__.'/../../../../system/library/razorpay-sdk/Razorpay.php';` to 
`require_once __DIR__.'/../../../system/library/razorpay-sdk/Razorpay.php';`?

**Comment by boja2015** [comment]
@mayankamencherla i tried but same error appears on checkout page step6

Fatal error: require_once(): Failed opening required '/catalog/controller/extension/payment/../../../system/library/razorpay-sdk/Razorpay.php' (include_path='.:/usr/local/php71/pear') in /catalog/controller/extension/payment/razorpay.php on line 3

**Comment by mayankamencherla** [comment]
@boja2015 Please replace:

`require_once __DIR__.'/../../../system/library/razorpay-sdk/Razorpay.php';` to 
`require_once __DIR__.'/../../../../system/library/razorpay-sdk/Razorpay.php';`

**Comment by boja2015** [comment]
i got the same error as mentioned in the first post

/index.php?route=payment/razorpay/callback


Fatal error: Uncaught Error: Class 'Controllerpaymentrazorpay' not found in 
/system/storage/modification/system/engine/action.php:43 Stack trace: #0 
/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #1 
/system/storage/modification/system/engine/action.php(51): ControllerStartupRouter->index() #2 
/system/engine/front.php(34): Action->execute(Object(Registry)) #3 
/system/engine/front.php(29): Front->execute(Object(Action)) #4 
/system/framework.php(103): Front->dispatch(Object(Action), Object(Action)) #5 
/system/startup.php(124): require_once('/home/machpowe/...') #6 
/index.php(19): start('catalog') #7 {main} thrown in /system/storage/modification/system/engine/action.php on line 43

**Comment by boja2015** [comment]
Hi
please update on the above issue

" Fatal error: Uncaught Error: Class 'Controllerpaymentrazorpay' not found in
/system/storage/modification/system/engine/action.php:43 Stack trace: #0 "

**Comment by mayankamencherla** [comment]
@boja2015 It seems like the installation wasn't performed correctly. Could you please delete all the files and ensure you merge the folders correctly? Please ensure that the contents of the extension folder is put in correctly to your opencart's extension folder?

**Comment by Joseph2398** [comment]
Fatal error: require(): Failed opening required 'Admin/view/index.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\3rdyearProject\SPSv1.1\PHPfile\Admin\RequestHandler\Route.php on line 12

Ive got an error on this. i think i used the correct path. How to solve it? Thank you.

**Comment by kajol22** [comment]
@Joseph2398 - Could you please tell the version of opencart you are using?

**Comment by ramth05** [comment]
Please try to use latest releases based on Open-cart version opencart2 : 3.0.0 and opencart3 : 4.0.0
