### ISSUE TITLE
Opencart 3.x support

### ISSUE THREAD

**Issue by Mayur-Wadpalliwar** [razorpay/razorpay-opencart#24]
We do not support Opencart 3.x at the moment but merchants are asking for the same?

**Comment by SatyaPenmetsa** [comment]
Razorpay Opencart 3.0.2.0 Extenstion
https://github.com/SatyaPenmetsa/Razorpay-Opencart-3.0.2.0-Extension

**Comment by captn3m0** [comment]
@SatyaPenmetsa Can you clarify what license the above code is under?

**Comment by Mayur-Wadpalliwar** [comment]
Ref: 115401

**Comment by mayankamencherla** [comment]
@captn3m0 @Mayur-Wadpalliwar Taking this up. Will test existing code and see if we can use this in our code base.

**Comment by mayankamencherla** [comment]
Plugin has a bug. Contacted developer. @SatyaPenmetsa

**Comment by SatyaPenmetsa** [comment]
Bugs fixed. @mayankamencherla

**Comment by mayankamencherla** [comment]
@captn3m0 Bug fixed.

**Comment by mayankamencherla** [comment]
Closing issue. Creating feature request.
