### ISSUE TITLE
Confirm order button not showing on checkout page

### ISSUE THREAD

**Issue by rajdeeporb** [razorpay/razorpay-opencart#25]
Am facing some issue with this extension on checkout page of my opencart version 2.3.0.2, not able to see "confirm order" button on the last step after choosing razorpay as payment method but its working fine with other payment gateways like COD etc.

**Comment by Mayur-Wadpalliwar** [comment]
@rajdeeporb As discussed over the email, this is resolved by re-installing the razorpay.tpl file.
