### ISSUE TITLE
Confirm Order Button is not Available after Integration with Opencart

### ISSUE THREAD

**Issue by lokesh2401** [razorpay/razorpay-opencart#26]
After integration of Razorpay Payment Gateway with Opencart, the Checkout does not show the confirm order Button.  
![image](https://user-images.githubusercontent.com/33391066/32418483-d8b982d6-c290-11e7-9ac5-bd7b49f077c0.png)

**Comment by Mayur-Wadpalliwar** [comment]
Hello Lokesh,

Please re-install razorpay.tpl template file under `catalog/view/theme/default/template` and it shall work

**Comment by Mayur-Wadpalliwar** [comment]
@lokesh2401

**Comment by lokesh2401** [comment]
I re-installed the one that's available here and it worked. The path was different. 
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=30298&sort=date_added
