### ISSUE TITLE
Need Razorpay Extension for Opencart 3x

### ISSUE THREAD

**Issue by vivek191991** [razorpay/razorpay-opencart#31]
Please develop Razorpay Extension for Opencart 3x.

**Comment by vivek191991** [comment]
I need a Razorpay Extension for Opencart 3x, I have my ecommerce on opencart 3, so just let me know if it is possible to release the version for oc3

**Comment by kajol22** [comment]
@vivek191991 You can refer to Opencart 3x docs here : https://github.com/SatyaPenmetsa/Razorpay-Opencart-3.0.2.0-Extension

**Comment by abelkbil** [comment]
The issue persist. I used this plugin
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=35771&filter_category_id=3&filter_download_id=56&sort=date_added

After the payment is made the the call back "index.php?route=extension/payment/razorpay/callback" showing this error "An error occured. Contact site administrator, please!".

The ticket reference for your request is #680063.
