### ISSUE TITLE
Will the plugin work with the new change with TSL1.1 or TSL 1.2

### ISSUE THREAD

**Issue by gauravjee** [razorpay/razorpay-opencart#33]
Hi receiving messages to check on Java update fo rTSL 1.1 and TSL 1.2 to work will the plugin require any change

**Comment by captn3m0** [comment]
It depends on your server configuration. Please check your Curl+OpenSSL version to verify whether it supports TLS1.1

Note that specifically for RHEL 6 and CentOS 6, there might be changes required even if your OS supports TLS1.1, since it won't enable it by default.

**Comment by ramth05** [comment]
No updates to closing this.
