### ISSUE TITLE
Doesn't work with any ajax quick checkout

### ISSUE THREAD

**Issue by prosenjeet123** [razorpay/razorpay-opencart#42]
It is not working when we use it with any ajax quick checkout. 
To replicate the issue:
When we try the checkout for the first time it works fine. The total amount(of razorpay popup) will be same as the checkout total amount. Suppose the total amount is ₹1028.02 the razorpay popup will ask you the same i.e ₹1028.02

But when you go back to home and add/remove products in the cart (total of ₹578 .00) and goto checkout. And then you press the checkout button the razorpay poup will show prev cart amount i.e ₹1028.02 instead of ₹578 something like this:
![image](https://user-images.githubusercontent.com/12624294/90982224-69662600-e583-11ea-9f22-a3231eac034b.png)

**Comment by ramth05** [comment]
> It is not working when we use it with any ajax quick checkout.
> To replicate the issue:
> When we try the checkout for the first time it works fine. The total amount(of razorpay popup) will be same as the checkout total amount. Suppose the total amount is ₹1028.02 the razorpay popup will ask you the same i.e ₹1028.02
> 
> But when you go back to home and add/remove products in the cart (total of ₹578 .00) and goto checkout. And then you press the checkout button the razorpay poup will show prev cart amount i.e ₹1028.02 instead of ₹578 something like this:
> ![image](https://user-images.githubusercontent.com/12624294/90982224-69662600-e583-11ea-9f22-a3231eac034b.png)

@prosenjeet123 , which version of opencart and razorpay you are using here?

**Comment by prosenjeet123** [comment]
> @prosenjeet123 , which version of opencart and razorpay you are using here?

We are using Version 3.0.3.2
with Ajax Quick Checkout 7.2.2 (ref :https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=15580)

**Comment by ramth05** [comment]
> > @prosenjeet123 , which version of opencart and razorpay you are using here?
> 
> We are using Version 3.0.3.2
> with Ajax Quick Checkout 7.2.2 (ref :https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=15580)

@prosenjeet123, are you using free version of plugin?

**Comment by prosenjeet123** [comment]
We have tried both versions Free/Pro. The issue is happening with both.
Currently we are using PRO.

Thanks

**Comment by prosenjeet123** [comment]
I am trying to debug the issue it seems the amount is not updating when we visit the checkout page for the second time. 
The get request for https://api.razorpay.com/v1/preferences?key_id=rxxxxxx&currency%5B0%5D=INR&order_id=order_FUYKs7hilIGuwk&amount=97706&_%5Bbuild%5D=10406&_%5Bcheckout_id%5D=FUYPMd5EGWnUiF&_%5Blibrary%5D=checkoutjs&_%5Bplatform%5D=browser&personalisation=1&checkcookie=1&_%5Brequest_index%5D=0

is sending wrong value of amount parameter, rest is fine.

Also this line of code could be the reason because when i add print  $order_info['currency_value'] is returning last checkout value.
Line 25 (catalog/...payment/razorpay.php):
 $order_info = $this->model_checkout_order->getOrder($this->session->data['order_id']);

**Comment by ramth05** [comment]
> I am trying to debug the issue it seems the amount is not updating when we visit the checkout page for the second time.
> The get request for https://api.razorpay.com/v1/preferences?key_id=rxxxxxx&currency%5B0%5D=INR&order_id=order_FUYKs7hilIGuwk&amount=97706&_%5Bbuild%5D=10406&_%5Bcheckout_id%5D=FUYPMd5EGWnUiF&_%5Blibrary%5D=checkoutjs&_%5Bplatform%5D=browser&personalisation=1&checkcookie=1&_%5Brequest_index%5D=0
> 
> is sending wrong value of amount parameter, rest is fine.
> 
> Also this line of code could be the reason because when i add print $order_info['currency_value'] is returning last checkout value.
> Line 25 (catalog/...payment/razorpay.php):
> $order_info = $this->model_checkout_order->getOrder($this->session->data['order_id']);

@prosenjeet123 , This means your 3rd party plugin unable to update Open cart order data, properly.

**Comment by prosenjeet123** [comment]
But the plugin itself is working 100% fine. 
I have also tried other ajax checkout modules but getting same issue.

Is there any fix ?

**Comment by ramth05** [comment]
> But the plugin itself is working 100% fine.
> I have also tried other ajax checkout modules but getting same issue.
> 
> Is there any fix ?

@prosenjeet123 , I didn't tried to debug it yet. But the only fix will be that if you are able to get proper updated order details at  this line some how --
Line 25 (catalog/...payment/razorpay.php):
$order_info = $this->model_checkout_order->getOrder($this->session->data['order_id']);

**Comment by prosenjeet123** [comment]
I wish i could figure out this but this is happening with all the ajax checkouts its been over 2 days now, I have been trying to figure out the issue. 
I have added some random parameters at the checkout url e.g abc.com/checkout?random=somerandomkey123123
to trick the browser that it is a fresh page and prevent caching issue. But didn't work. 

The issue is vanishing when we double refresh the page. This is a very critical issued and the sales has been blocked due to this. 
The module is best selling module in opencart around 80% opencart users are using the module just like journal. So the razorpay must work with this module to support the entire community.

Appreciate your help!

Thanks

**Comment by prosenjeet123** [comment]
> > But the plugin itself is working 100% fine.
> > I have also tried other ajax checkout modules but getting same issue.
> > Is there any fix ?
> 
> @prosenjeet123 , I didn't tried to debug it yet. But the only fix will be that if you are able to get proper updated order details at this line some how --
> Line 25 (catalog/...payment/razorpay.php):
> $order_info = $this->model_checkout_order->getOrder($this->session->data['order_id']);

Will you be able to tell me the line of code where you are sending the GET request for https://api.razorpay.com/v1/preferences?key_id=xxxxxx&currency%5B0%5D=INR&order_id=order_FUgz0YXK0ZG30t&amount=**151802**&_%5Bbuild%5D=10406&_%5Bcheckout_id%5D=FUgzGSbZmwPYz6&_%5Blibrary%5D=checkoutjs&_%5Bplatform%5D=browser&personalisation=1&checkcookie=1&_%5Brequest_index%5D=1

I want to change the parameter variable of amount. 
I can't figure out the parameters you are sending in this line 314 (catalog/...payment/razorpay):
$response = Requests::get($api->getBaseUrl() . 'preferences?key_id=' . $api->getKey());

where are the parameters here?

**Comment by prosenjeet123** [comment]
Well i have closed the issue by replacing all the values of total
Find : $order_info['total'] & $order['total']
Replaced with: $this->session->data['total']

The order info wasn't returning correct values of total amount so this is the quick fix for this issue. Hope you will find a permanent fix for this in the future releases.
