### ISSUE TITLE
Invalid signature passed

### ISSUE THREAD

**Issue by prosenjeet123** [razorpay/razorpay-opencart#44]
All of our payments are throwing the same error now:

Invalid signature passed Payment Failed! Check Razorpay dashboard for details of Payment Id:pay_FZSJlTJYjOd3lP
The dashboard is showing "captured" but opencart is returning failed status along with this message.
Is this a module issue or the gateway itself?

![image](https://user-images.githubusercontent.com/12624294/92319236-b93cf680-f033-11ea-8884-a1099945ca27.png)

**Comment by ramth05** [comment]
@prosenjeet123 , Can you please let us know which version of plugin and opencart you are facing this issue?

**Comment by ramth05** [comment]
closing it now as no reply. Please feel free to re-open it.
