### ISSUE TITLE
Installation of 4.0.1 in opencart 3.0.3.2 is raising internal server error.

### ISSUE THREAD

**Issue by MrityunjaiKumar** [razorpay/razorpay-opencart#45]
While installing razorpay plugin, opencart is showing internal server error. But on refresh it is showing in install history. Is there some bug with it and is it save to proceed?

**Comment by ramth05** [comment]
@MrityunjaiKumar , Can you please let us know which version of opencart and plugin you facing the issue.

**Comment by ramth05** [comment]
@MrityunjaiKumar , Can you please let us know what is the exact issue and if there is any screen shot you can share to help us.

**Comment by ramth05** [comment]
closing it now as no reply. Please feel free to re-open it.
