### ISSUE TITLE
Feature request - Direct option for UPI payment

### ISSUE THREAD

**Issue by skyviewmedia** [razorpay/razorpay-opencart#48]
Hi, currently when the Razorpay module is install in Opencart (I am using version 2.0.3.1) the option for using Razorpay as payment gateway shows up under the payment options. When using this option, the customer can access all of the payment options which are enabled for our id.
I want to offer a separate option for UPI payment from the Opencart payment options, which if selected by the user, it will load Razorpay payment gateway with pre-selected UPI option as default & all other options hidden.
Is it possible to achieve this ?

**Comment by giridhar1994** [comment]
@skyviewmedia Yes, it is possible to disable the required payment methods on the checkout. You can raise a concern on the Razorpay dashboard by raising a request. So the concerned team would process [Link](https://razorpay.com/docs/payment-gateway/dashboard-guide/support/#contact-support)
