### ISSUE TITLE
Razorpay is not showing in checkout

### ISSUE THREAD

**Issue by ravidevt** [razorpay/razorpay-opencart#49]
Hi,

I have updated 4.0.1 in my opencart version 3.0.2.0, But Razorpay is not showing in checkout. I am suing boss custome theme.

**Comment by ramth05** [comment]
@ravidevt , The plugin build on base theme and as per opencart guidelines. if it's not working on some Ajax based themes then the plugin requires customisation  based on theme.

Closing it now. Please feel free to re-open if it's not working properly with basic theme and basic opencart installation.
