### ISSUE TITLE
Invalid signature passed

### ISSUE THREAD

**Issue by shaikhnedab** [razorpay/razorpay-opencart#50]
I am getting exactly same issue as #44.
![92319236-b93cf680-f033-11ea-8884-a1099945ca27](https://user-images.githubusercontent.com/55206494/103545917-42701700-4ec8-11eb-8e1a-aa67b62cb61a.png)

Its 50/50 chance either I get the error or I don't. The money gets deducted from account and the user as well as admin gets order email from opencart but with ``Status = Failed`` even with confirmed payment.

Note: I have removed the svg image file link from the ``/catalog/language/en-gb/extension/payment/razorpay.php`` as it was messing with the invoice causing invoice page to break.

My Installation: 
OpenCart Version: ``3.0.3.3``
razorpay-extension  Version: ``4.0.1``

**Comment by shaikhnedab** [comment]
Found another issue if I enable razorpay extension and try to apply coupon it breaks the checkout and the page stuck on circle loading. and if I try to reload the page I get following error.
![error](https://user-images.githubusercontent.com/55206494/103689948-fef5d580-4fb9-11eb-92f1-46c9b807aa7e.png)
After disabling razorpay everything works fine.

My Installation:
OpenCart Version: ``3.0.3.3``
razorpay-extension Version:`` 4.0.1``

**Comment by codex-pro** [comment]
I M GETTING SAME ERROR

**Comment by ramth05** [comment]
> I M GETTING SAME ERROR

@codex-pro,  Can you please share test site details where you facing this issue.

**Comment by codex-pro** [comment]
qualyinvesto.com if user cancel the payment in mid it goes to end less loop we have refresh it to make it work

> > I M GETTING SAME ERROR
> 
> @codex-pro, Can you please share test site details where you facing this issue.

qualyinvesto.com if user cancel the payment in mid it goes to end less loop we have refresh it to make it work

**Comment by ramth05** [comment]
> qualyinvesto.com

@codex-pro , looks like some JS error near **Facebook Pixel Code** , Can you please correct it .
` <script type="text/javascript">
<script>`

**Comment by ramth05** [comment]
> qualyinvesto.com

@codex-pro , looks like some JS error near **Facebook Pixel Code** , Can you please correct it .
` <script type="text/javascript">
<script>`

**Comment by codex-pro** [comment]
> > qualyinvesto.com
> 
> @codex-pro , looks like some JS error near **Facebook Pixel Code** , Can you please correct it .
> ` <script type="text/javascript">
> 
> <script>`

removed script ..still same issue

**Comment by ramth05** [comment]
> > > qualyinvesto.com
> > 
> > 
> > @codex-pro , looks like some JS error near **Facebook Pixel Code** , Can you please correct it .
> > ` <script type="text/javascript">
> > <script>`
> 
> removed script ..still same issue

@codex-pro, The loading screen not from the plugin, looks like you have made some customisation in theme etc which creating this issue. 

Please test the plugin with open-cart blank site and default theme.

**Comment by ramth05** [comment]
@codex-pro , Please try to use latest release 4.0.2 .
