### ISSUE TITLE
Razorpay Capturing issue

### ISSUE THREAD

**Issue by Hari1202-hub** [razorpay/razorpay-opencart#57]
Sometimes, In razorpay payment is got captured. but its not reflecting on opencart. Let me know, how to solve this issue.

**Comment by abdulwahidsharief** [comment]
@Hari1202-hub in few cases when customer network is unstable or server processing is slow callback(thank you order received page) can fail. please use Webhook to resolve this https://betasite.razorpay.com/docs/razorpay/IN/payments-pg-plugins-opencart/payments/payment-gateway/ecommerce-plugins/open-cart/build-integration/#step-1-install-plugin
